<a href="https://colab.research.google.com/github/marwankashef/Association-Rules/blob/master/Association_Rules_%26_Apriori_Applications.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [0]:
import pandas as pd
import mlxtend
import os

from mlxtend.preprocessing import TransactionEncoder
from mlxtend.frequent_patterns import apriori
from mlxtend.frequent_patterns import association_rules

from IPython.core.interactiveshell import InteractiveShell
InteractiveShell.ast_node_interactivity = "all"

In [0]:
dataset = [['Pita Bread', 'Hummus', 'Thyme', 'Eggs', 'Olive Oil', 'Shawarma Meat'],
           ['Garlic Sauce', 'Hummus', 'Thyme', 'Eggs', 'Olive Oil', 'Shawarma Meat'],
           ['Lamb', 'Hummus', 'Lamb', 'Eggs', 'Olive Oil', 'Chicken'],      
           ['Lamb', 'Olive Oil', 'Pickled Turnips', 'Pickles', 'Olive Oil', 'Chicken'],               
           ['Pita Bread', 'Cucumber', 'Eggs', 'Olive Oil','Hummus','Thyme'],
           ['Pita Bread', 'Olive Oil', 'Eggs', 'Eggs','Pickled Turnips','Salt'],
           ['Pita Bread', 'Baba Ganouj', 'Corn', 'Eggs', 'Shawarma Meat','Thyme'],
           ['Corn', 'Hummus', 'Hummus', 'Eggs', 'Baklava', 'Olive Oil']]

dataset

[['Pita Bread', 'Hummus', 'Thyme', 'Eggs', 'Olive Oil', 'Shawarma Meat'],
 ['Garlic Sauce', 'Hummus', 'Thyme', 'Eggs', 'Olive Oil', 'Shawarma Meat'],
 ['Lamb', 'Hummus', 'Lamb', 'Eggs', 'Olive Oil', 'Chicken'],
 ['Lamb', 'Olive Oil', 'Pickled Turnips', 'Pickles', 'Olive Oil', 'Chicken'],
 ['Pita Bread', 'Cucumber', 'Eggs', 'Olive Oil', 'Hummus', 'Thyme'],
 ['Pita Bread', 'Olive Oil', 'Eggs', 'Eggs', 'Pickled Turnips', 'Salt'],
 ['Pita Bread', 'Baba Ganouj', 'Corn', 'Eggs', 'Shawarma Meat', 'Thyme'],
 ['Corn', 'Hummus', 'Hummus', 'Eggs', 'Baklava', 'Olive Oil']]

In [0]:
dataset_csv = pd.DataFrame(dataset)
dataset_csv.to_csv (r'dataset.csv', index = None, header=True)

In [0]:
te = TransactionEncoder()
te_ary = te.fit(dataset).transform(dataset)
df = pd.DataFrame(te_ary, columns=te.columns_)
frequent_itemsets = apriori(df, min_support=0.001, use_colnames=True)

frequent_itemsets

     support                                           itemsets
0      0.125                                      (Baba Ganouj)
1      0.125                                          (Baklava)
2      0.250                                          (Chicken)
3      0.250                                             (Corn)
4      0.125                                         (Cucumber)
..       ...                                                ...
262    0.125  (Olive Oil, Shawarma Meat, Hummus, Thyme, Pita...
263    0.125  (Corn, Baba Ganouj, Eggs, Shawarma Meat, Thyme...
264    0.125  (Olive Oil, Cucumber, Eggs, Hummus, Thyme, Pit...
265    0.125  (Olive Oil, Eggs, Shawarma Meat, Hummus, Thyme...
266    0.125  (Olive Oil, Eggs, Shawarma Meat, Hummus, Thyme...

[267 rows x 2 columns]

In [0]:
arules = association_rules(frequent_itemsets, metric="confidence", min_threshold=0.001)

arules

,antecedents,consequents,antecedent support,consequent support,support,confidence,lift,leverage,conviction
0,(Corn),(Baba Ganouj),0.250,0.125,0.125,0.500000,4.000000,0.093750,1.750000
1,(Baba Ganouj),(Corn),0.125,0.250,0.125,1.000000,4.000000,0.093750,inf
2,(Baba Ganouj),(Eggs),0.125,0.875,0.125,1.000000,1.142857,0.015625,inf
3,(Eggs),(Baba Ganouj),0.875,0.125,0.125,0.142857,1.142857,0.015625,1.020833
4,(Pita Bread),(Baba Ganouj),0.500,0.125,0.125,0.250000,2.000000,0.062500,1.166667
...,...,...,...,...,...,...,...,...,...
2661,(Eggs),"(Olive Oil, Shawarma Meat, Hummus, Thyme, Pita...",0.875,0.125,0.125,0.142857,1.142857,0.015625,1.020833
2662,(Shawarma Meat),"(Olive Oil, Eggs, Hummus, Thyme, Pita Bread)",0.375,0.250,0.125,0.333333,1.333333,0.031250,1.125000
2663,(Hummus),"(Olive Oil, Eggs, Shawarma Meat, Thyme, Pita B...",0.625,0.125,0.125,0.200000,1.600000,0.046875,1.093750
2664,(Thyme),"(Olive Oil, Eggs, Shawarma Meat, Hummus, Pita ...",0.500,0.125,0.125,0.250000,2.000000,0.062500,1.166667
2665,(Pita Bread),"(Olive Oil, Eggs, Shawarma Meat, Hummus, Thyme)",0.500,0.250,0.125,0.250000,1.000000,0.000000,1.000000

In [0]:
arules["antecedent_len"] = arules["antecedents"].apply(lambda x: len(x))
arules

,antecedents,consequents,antecedent support,consequent support,support,confidence,lift,leverage,conviction,antecedent_len
0,(Corn),(Baba Ganouj),0.250,0.125,0.125,0.500000,4.000000,0.093750,1.750000,1
1,(Baba Ganouj),(Corn),0.125,0.250,0.125,1.000000,4.000000,0.093750,inf,1
2,(Baba Ganouj),(Eggs),0.125,0.875,0.125,1.000000,1.142857,0.015625,inf,1
3,(Eggs),(Baba Ganouj),0.875,0.125,0.125,0.142857,1.142857,0.015625,1.020833,1
4,(Pita Bread),(Baba Ganouj),0.500,0.125,0.125,0.250000,2.000000,0.062500,1.166667,1
...,...,...,...,...,...,...,...,...,...,...
2661,(Eggs),"(Olive Oil, Shawarma Meat, Hummus, Thyme, Pita...",0.875,0.125,0.125,0.142857,1.142857,0.015625,1.020833,1
2662,(Shawarma Meat),"(Olive Oil, Eggs, Hummus, Thyme, Pita Bread)",0.375,0.250,0.125,0.333333,1.333333,0.031250,1.125000,1
2663,(Hummus),"(Olive Oil, Eggs, Shawarma Meat, Thyme, Pita B...",0.625,0.125,0.125,0.200000,1.600000,0.046875,1.093750,1
2664,(Thyme),"(Olive Oil, Eggs, Shawarma Meat, Hummus, Pita ...",0.500,0.125,0.125,0.250000,2.000000,0.062500,1.166667,1
2665,(Pita Bread),"(Olive Oil, Eggs, Shawarma Meat, Hummus, Thyme)",0.500,0.250,0.125,0.250000,1.000000,0.000000,1.000000,1

In [0]:
arules.to_csv (r'arules.csv', index = None, header=True)

In [0]:
# High Support & High Confidence

HighSupport_HighConfidence = arules[ (arules['support'] >= 0.70) &
       (arules['confidence'] > 0.80)]

In [0]:
# High Support & Low Confidence

HighSupport_LowConfidence =arules[ (arules['support'] >= 0.50) &
       (arules['confidence'] <= 0.60)]

In [0]:
# Low Support & High Confidence

LowSupport_HighConfidence = arules[ (arules['support'] <= 0.15) &
       (arules['confidence'] >= 0.50)]

In [0]:
# Low Support & High Confidence

LowSupport_HighConfidence = arules[ (arules['support'] <= 0.15) &
       (arules['confidence'] >= 0.9)]